name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Repository checkout
      uses: actions/checkout@v2
    - name: Build Swift Package (macOS)
      run: swift build -v
    - name: Run tests in Swift Package (macOS)
      run: swift test -v
    - name: Build Swift Package (iOS)
      run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild build-for-testing -scheme MotorControl -destination "platform=iOS Simulator,OS=15.2,name=iPhone 12" | xcpretty
    - name: Run tests in Swift Package (iOS)
      run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild test-without-building -scheme MotorControl -destination "platform=iOS Simulator,OS=15.2,name=iPhone 12" | xcpretty
