name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-11
    steps:
    - name: Repository checkout
      uses: actions/checkout@v2
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
    - name: Force Xcode 13.2
      run: sudo xcode-select -switch /Applications/Xcode_13.2.app
    - name: Build for iOS
      run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild build-for-testing -scheme MotorControl -destination "platform=iOS Simulator,OS=15.2,name=iPhone 12" | xcpretty
    - name: Run iOS tests
      run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild test-without-building -scheme MotorControl -destination "platform=iOS Simulator,OS=15.2,name=iPhone 12" | xcpretty
